import { Product, Space, Sheen, Texture, Method } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: '1. 卡拉拉細灰泥 (Carrara Fine)',
    category: 'Ancient Plaster',
    description: '如頂級絲綢般細膩，能感受灰泥密度與工藝的光滑面。',
    spaces: [Space.INDOOR_WALL],
    sheen: Sheen.GLOSSY,
    texture: Texture.SMOOTH,
    method: Method.PRO,
    pricePerPing: 10500,
    features: ['平滑亮面', '大理石般光澤'],
    purchaseUrl: 'https://pamaterial.com/carrara/'
  },
  {
    id: '2',
    name: '2. 卡拉拉中灰泥 (Carrara Medium)',
    category: 'Ancient Plaster',
    description: '追求如大理石般光澤、具備微反光特性的亮光。',
    spaces: [Space.INDOOR_WALL, Space.OUTDOOR_WALL],
    sheen: Sheen.GLOSSY,
    texture: Texture.SMOOTH,
    method: Method.PRO,
    pricePerPing: 10500,
    features: ['平滑亮面', '微反光'],
    purchaseUrl: 'https://pamaterial.com/carrara/'
  },
  {
    id: '3',
    name: '3. 卡拉拉粗灰泥 (Carrara Coarse)',
    category: 'Ancient Plaster',
    description: '優雅內斂、柔和的平光，帶有細緻的礦物顆粒感。',
    spaces: [Space.INDOOR_WALL],
    sheen: Sheen.MATTE,
    texture: Texture.SMOOTH,
    method: Method.PRO,
    pricePerPing: 10500,
    features: ['平滑平光', '礦物顆粒'],
    purchaseUrl: 'https://pamaterial.com/carrara/'
  },
  {
    id: '12',
    name: '12. 威尼斯外牆',
    category: 'Ancient Plaster',
    description: '專為室外壁面設計的配方，具備極佳的耐候性與經典美感。',
    spaces: [Space.OUTDOOR_WALL],
    sheen: Sheen.MATTE,
    texture: Texture.SMOOTH,
    method: Method.PRO,
    pricePerPing: 10500,
    features: ['室外專用', '平滑平光', '耐候性佳'],
    purchaseUrl: 'https://pamaterial.com/venice/'
  },
  {
    id: '4',
    name: '4. Wabi-sabi 灰泥',
    category: 'Ancient Plaster',
    description: '深沉消光，營造歷史感與侘寂之美，帶有時間刻痕的粗糙面。',
    spaces: [Space.INDOOR_WALL],
    sheen: Sheen.MATTE,
    texture: Texture.ROUGH,
    method: Method.PRO,
    pricePerPing: 10000,
    features: ['顆粒消光', '侘寂風格', '礦物顆粒'],
    purchaseUrl: 'https://pamaterial.com/wabi-sabi/'
  },
  {
    id: '5',
    name: '5. 銀蔥灰泥',
    category: 'Ancient Plaster',
    description: '平滑平光，內含礦物石粉顆粒，低調奢華。',
    spaces: [Space.INDOOR_WALL, Space.OUTDOOR_WALL],
    sheen: Sheen.MATTE,
    texture: Texture.SMOOTH,
    method: Method.PRO,
    pricePerPing: 10000,
    features: ['平滑平光', '礦物顆粒'],
    purchaseUrl: 'https://pamaterial.com/mica/'
  },
  {
    id: '6',
    name: '6. 帕通灰泥 (Pastellone)',
    category: 'Ancient Plaster',
    description: '室內壁面的經典選擇，平滑且具備優良質地。',
    spaces: [Space.INDOOR_WALL, Space.OUTDOOR_WALL],
    sheen: Sheen.MATTE,
    texture: Texture.SMOOTH,
    method: Method.PRO,
    pricePerPing: 10500,
    features: ['平滑平光', '經典質感'],
    purchaseUrl: 'https://pamaterial.com/pastellone/'
  },
  {
    id: '6.1',
    name: '6.1 帕通灰泥 (Pastellone)',
    category: 'Ancient Plaster',
    description: '專為浴室與地坪設計，堅固且耐久的基礎。',
    spaces: [Space.BATHROOM, Space.FLOOR, Space.FURNITURE],
    sheen: Sheen.MATTE,
    texture: Texture.SMOOTH,
    method: Method.PRO,
    pricePerPing: 13500,
    features: ['浴室/地坪專用', '高耐用度'],
    purchaseUrl: 'https://pamaterial.com/pastellone/'
  },
  {
    id: '7',
    name: '7. 磐石灰泥',
    category: 'Ancient Plaster',
    description: '毛孔明顯，呈現歲月沉澱的粗獷感，適合室內外及特殊空間。',
    spaces: [Space.INDOOR_WALL, Space.OUTDOOR_WALL, Space.FURNITURE, Space.BATHROOM],
    sheen: Sheen.MATTE,
    texture: Texture.ROUGH,
    method: Method.PRO,
    pricePerPing: 15000,
    features: ['毛孔/平光', '粗獷質感', '浴室適用'],
    purchaseUrl: 'https://pamaterial.com/stone/'
  },
  {
    id: '8',
    name: '8. 擁抱古法 (Embrace Ancient)',
    category: 'Lime Paint',
    description: '尊循古法施作步驟，表面質地具顆粒感的石灰漆。適合DIY，亦可用於地坪基礎。',
    spaces: [Space.INDOOR_WALL, Space.OUTDOOR_WALL, Space.FLOOR, Space.BATHROOM],
    sheen: Sheen.MATTE,
    texture: Texture.ROUGH,
    method: Method.DIY,
    pricePerPing: 1000,
    features: ['顆粒感', 'DIY首選', '高CP值'],
    purchaseUrl: 'https://shop.pamaterial.com/lime/'
  },
  {
    id: '9',
    name: '9. 精油強身 (Essential Oil)',
    category: 'Lime Paint',
    description: '含有精油成分達到良好的防霉抗菌功效，表面平滑。',
    spaces: [Space.INDOOR_WALL],
    sheen: Sheen.MATTE,
    texture: Texture.SMOOTH,
    method: Method.DIY,
    pricePerPing: 1150,
    features: ['消光面', '精油抗菌', '平滑'],
    purchaseUrl: 'https://shop.pamaterial.com/essentialoil/'
  },
  {
    id: '10',
    name: '10. 純素主義 (Vegan)',
    category: 'Lime Paint',
    description: '使用全素配方，適合Vegan，表面平滑消光。',
    spaces: [Space.INDOOR_WALL],
    sheen: Sheen.MATTE,
    texture: Texture.SMOOTH,
    method: Method.DIY,
    pricePerPing: 950,
    features: ['消光面', '純素配方'],
    purchaseUrl: 'https://shop.pamaterial.com/vegan/'
  },
  {
    id: '11',
    name: '11. 摩洛哥灰泥 (Tadelakt)',
    category: 'Ancient Plaster',
    description: '傳統摩洛哥風格，平滑平光，適合各類空間包含浴室與家具範疇。',
    spaces: [Space.INDOOR_WALL, Space.OUTDOOR_WALL, Space.BATHROOM, Space.FURNITURE],
    sheen: Sheen.MATTE,
    texture: Texture.SMOOTH,
    method: Method.PRO,
    pricePerPing: 13500,
    features: ['平滑平光', '多用途'],
    purchaseUrl: 'https://pamaterial.com/tadelakt/'
  }
];